FROM nvidia/cuda:12.9.1-devel-ubuntu24.04

# sm_75=Turing, sm_80/86=Ampere, sm_89=Ada, sm_90=Hopper
# CUDA 12.9 deprecates offline compilation for architectures < sm_75
ARG CUDA_ARCHITECTURES=75

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -yq && apt-get install -yq \
    build-essential git cmake ninja-build \
    libpng-dev libjpeg-dev libtiff-dev \
    libglu1-mesa-dev libglew-dev libglfw3-dev \
    libboost-iostreams-dev libboost-program-options-dev \
    libboost-system-dev libboost-serialization-dev \
    libopencv-dev \
    libcgal-dev \
    libomp-dev \
    && rm -rf /var/lib/apt/lists/*

# Eigen 3.4
RUN git clone --depth 1 --branch 3.4 https://gitlab.com/libeigen/eigen.git /tmp/eigen && \
    cmake -S /tmp/eigen -B /tmp/eigen_build \
        -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda && \
    cmake --build /tmp/eigen_build --target install && \
    rm -rf /tmp/eigen /tmp/eigen_build

# VCGLib
RUN git clone --depth 1 https://github.com/cdcseacave/VCG.git /vcglib

# Copy local openMVS source
WORKDIR /openmvs_src
COPY . .

# Build
RUN cmake -S . -B /openmvs_build -GNinja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr/local \
    -DVCG_ROOT=/vcglib \
    -DOpenMVS_USE_CUDA=ON \
    -DOpenMVS_MAX_CUDA_COMPATIBILITY=OFF \
    -DCMAKE_CUDA_ARCHITECTURES=${CUDA_ARCHITECTURES} \
    -DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs \
    -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda \
    -DCUDA_INCLUDE_DIRS=/usr/local/cuda/include \
    -DOpenMVS_USE_BREAKPAD=OFF \
    -DOpenMVS_ENABLE_TESTS=OFF && \
    cmake --build /openmvs_build -j$(nproc) && \
    cmake --install /openmvs_build && \
    rm -rf /openmvs_build

ENV PATH="/usr/local/bin/OpenMVS:$PATH"
